//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockChainTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int transactionId { get; set; }
        public Nullable<int> blockId { get; set; }
        public string fromAddress { get; set; }
        public string toAddress { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual Block Block { get; set; }
    }
}
